server:
  port: 9001
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/users_ms?serverTimezone=America/Bogota&allowPublicKeyRetrieval=false
    username: root
    password: "jiren"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
